### ISSUE TITLE
Styling HTML signature messes up preferences section

### ISSUE THREAD

**Issue by ayushyamitabh** [Foundry376/Mailspring#964]
The styling being applied to a signature also applies to the whole preferences window. Adding this to the signature HTML is what messed it up:

```css
<style>
*{
display: inline !important; 
/* removing this line fixed it - without the !important, the button bar messes up. Adding the !important breaks everything.*/
}
</style>
```
##### What operating system are you using?
elementary OS Loki

##### What version of Mailspring are you using?
1.2.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No plugins.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Nope.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![messed up](https://user-images.githubusercontent.com/26289557/42179017-768a4ace-7e00-11e8-8978-11a24d443c87.png)
